apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.metadata.namespace}}
  name: {{ .Values.metadata.name}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.metadata.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name}}
    spec:
      containers:
        - name: {{ .Values.metadata.name}}
          image: {{ .Values.image.repository}}:{{ .Chart.AppVersion}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80