apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.config.name}}
  labels:
    app: {{.Values.storage.name}}
data:
  POSTGRES_DB: {{.Values.config.database}}
  POSTGRES_USER: {{.Values.config.user}}
  POSTGRES_PASSWORD: {{.Values.config.password}}