apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.metadata.name}}
  namespace: {{.Values.metadata.namespace}}
  labels:
    app: {{.Values.metadata.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.metadata.name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.metadata.name}}
    spec:
      containers:
        - image: postgres:13.3
          name: {{.Values.metadata.name}}
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: {{.Values.config.name}}
          ports:
            - containerPort: {{.Values.config.port}}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{.Values.storage.name}}
      volumes:
        - name: {{.Values.storage.name}}
          persistentVolumeClaim:
            claimName: {{.Values.storage.claimName}}