apiVersion: v1
kind: Service
metadata:
  name: {{.Values.metadata.name}}
  namespace: {{.Values.metadata.namespace}}
  labels:
    app: {{.Values.metadata.name}}
spec:
  selector:
    app: {{.Values.metadata.name}}
  ports:
    - port: {{.Values.config.port}}