apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-todo-database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: go-todo
    server: {{ .Values.spec.destination.server}}
  project: default
  source:
    chart: go-todo/database
    repoURL: {{ .Values.spec.source.repoURL}}
    targetRevision: {{ .Values.spec.source.targetRevision }}