apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-todo-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: go-todo
    server: {{ .Values.spec.destination.server}}
  project: default
  source:
    path: go-todo/frontend
    repoURL: {{ .Values.spec.source.repoURL}}
    targetRevision: {{ .Values.spec.source.targetRevision }}