apiVersion: v1
kind: ConfigMap
metadata:
  name: go-todo-backend-config
  namespace: go-todo
data:
  DB_HOST: {{.Values.config.database.host | quote}}
  DB_PORT: {{.Values.config.database.port | quote}}
  DB_USER: {{.Values.config.database.user | quote}}
  DB_PASSWORD: {{.Values.config.database.password | quote}}
  DB_NAME: {{.Values.config.database.database | quote}}