apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.metadata.namespace}}
  name: {{ .Values.metadata.name}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.metadata.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name}}
    spec:
      containers:
        - name: {{ .Values.metadata.name}}
          image: {{ .Values.image.repository}}:{{ .Chart.AppVersion}}
          env:
            - name: DB_HOST
              value: {{.Values.config.database.host}}
            - name: DB_PORT
              value: {{.Values.config.database.port}}
            - name: DB_USER
              value: {{.Values.config.database.user}}
            - name: DB_PASSWORD
              value: {{.Values.config.database.password}}
            - name: DB_NAME
              value: {{.Values.config.database.database}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.config.container.port}}
      imagePullSecrets:
        - name: gitlab-registry-secret