apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name}}
  namespace: {{ .Values.metadata.namespace}}
spec:
  selector:
    app: {{ .Values.metadata.name}}
  ports:
    - protocol: TCP
      port: {{.Values.config.container.port}}
      targetPort: {{.Values.config.container.targetPort}}