replicaCount: 1

image:
  repository: registry.gitlab.com/chrupek.tech/go-todo/go-todo

metadata:
  name: go-todo-backend
  namespace: go-todo

config:
  name: go-todo-backend-config
  container:
    port: 80
    targetPort: 80
  database:
    host: "go-todo-database"
    database: "golang"
    user: "golang"
    password: "password"
    port: "5432"